# Generated by Django 4.2.3 on 2023-07-27 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('month', models.CharField(default='', max_length=50)),
                ('year', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Basic', models.CharField(default='', max_length=100)),
                ('nature', models.CharField(default='', max_length=100)),
                ('communications', models.CharField(default='', max_length=100)),
                ('meal', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('Total', models.CharField(default='', max_length=100)),
                ('Bonuses', models.CharField(default='', max_length=100)),
                ('extra', models.CharField(default='', max_length=100)),
                ('Other_allowances', models.CharField(default='', max_length=100)),
                ('Total_accruals', models.CharField(default='', max_length=100)),
                ('Sanctions', models.CharField(default='', max_length=100)),
                ('Absences', models.CharField(default='', max_length=100)),
                ('Insurances', models.CharField(default='', max_length=100)),
                ('income_tax', models.CharField(default='', max_length=100)),
                ('Medical_service', models.CharField(default='', max_length=100)),
                ('Loans', models.CharField(default='', max_length=100)),
                ('Discounts', models.CharField(default='', max_length=100)),
                ('car', models.CharField(default='', max_length=100)),
                ('another', models.CharField(default='', max_length=100)),
                ('Total_deductions', models.CharField(default='', max_length=100)),
                ('Net_salary_payable', models.CharField(default='', max_length=100)),
                ('personal_loan', models.CharField(default='', max_length=100)),
                ('net', models.CharField(default='', max_length=100)),
                ('Reward_days', models.CharField(default='', max_length=100)),
                ('Overtime_hours', models.CharField(default='', max_length=100)),
                ('Absence_with_permission', models.CharField(default='', max_length=100)),
                ('Late_hours', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
