# Generated by Django 4.2.3 on 2023-07-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=50)),
                ('mony', models.CharField(max_length=50)),
                ('variable', models.CharField(max_length=50)),
                ('allwork', models.CharField(max_length=50)),
                ('tamin', models.CharField(max_length=50)),
                ('falsework', models.CharField(max_length=50)),
                ('allfalse', models.CharField(max_length=50)),
                ('allmony', models.CharField(max_length=50)),
            ],
        ),
    ]
